/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProofOfCredit {
      
    export type BorrowerStruct = {creditScore: BigNumberish, totalRepayments: BigNumberish, registered: boolean}

    export type BorrowerStructOutput = [creditScore: bigint, totalRepayments: bigint, registered: boolean] & {creditScore: bigint, totalRepayments: bigint, registered: boolean }
  
    }

  export interface ProofOfCreditInterface extends Interface {
    getFunction(nameOrSignature: "borrowers" | "getBorrower" | "getEligibility" | "initialOwner" | "lenders" | "owner" | "recordRepayment" | "registerBorrower" | "registerLender" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BorrowerRegistered" | "LenderRegistered" | "OwnershipTransferred" | "RepaymentRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'borrowers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getBorrower', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEligibility', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'lenders', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordRepayment', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerBorrower', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerLender', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'borrowers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrower', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lenders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordRepayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBorrower', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerLender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace BorrowerRegisteredEvent {
      export type InputTuple = [borrower: AddressLike];
      export type OutputTuple = [borrower: string];
      export interface OutputObject {borrower: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LenderRegisteredEvent {
      export type InputTuple = [lender: AddressLike];
      export type OutputTuple = [lender: string];
      export interface OutputObject {lender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepaymentRecordedEvent {
      export type InputTuple = [borrower: AddressLike, newCreditScore: BigNumberish, totalRepayments: BigNumberish];
      export type OutputTuple = [borrower: string, newCreditScore: bigint, totalRepayments: bigint];
      export interface OutputObject {borrower: string, newCreditScore: bigint, totalRepayments: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProofOfCredit extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProofOfCredit;
    waitForDeployment(): Promise<this>;

    interface: ProofOfCreditInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    borrowers: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, boolean] & {creditScore: bigint, totalRepayments: bigint, registered: boolean }],
      'view'
    >
    

    
    getBorrower: TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [ProofOfCredit.BorrowerStructOutput],
      'view'
    >
    

    
    getEligibility: TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initialOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lenders: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordRepayment: TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerBorrower: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    registerLender: TypedContractMethod<
      [lender: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'borrowers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, boolean] & {creditScore: bigint, totalRepayments: bigint, registered: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrower'): TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [ProofOfCredit.BorrowerStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEligibility'): TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initialOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lenders'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordRepayment'): TypedContractMethod<
      [borrowerAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerBorrower'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerLender'): TypedContractMethod<
      [lender: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BorrowerRegistered'): TypedContractEvent<BorrowerRegisteredEvent.InputTuple, BorrowerRegisteredEvent.OutputTuple, BorrowerRegisteredEvent.OutputObject>;
getEvent(key: 'LenderRegistered'): TypedContractEvent<LenderRegisteredEvent.InputTuple, LenderRegisteredEvent.OutputTuple, LenderRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RepaymentRecorded'): TypedContractEvent<RepaymentRecordedEvent.InputTuple, RepaymentRecordedEvent.OutputTuple, RepaymentRecordedEvent.OutputObject>;

    filters: {
      
      'BorrowerRegistered(address)': TypedContractEvent<BorrowerRegisteredEvent.InputTuple, BorrowerRegisteredEvent.OutputTuple, BorrowerRegisteredEvent.OutputObject>;
      BorrowerRegistered: TypedContractEvent<BorrowerRegisteredEvent.InputTuple, BorrowerRegisteredEvent.OutputTuple, BorrowerRegisteredEvent.OutputObject>;
    

      'LenderRegistered(address)': TypedContractEvent<LenderRegisteredEvent.InputTuple, LenderRegisteredEvent.OutputTuple, LenderRegisteredEvent.OutputObject>;
      LenderRegistered: TypedContractEvent<LenderRegisteredEvent.InputTuple, LenderRegisteredEvent.OutputTuple, LenderRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RepaymentRecorded(address,uint256,uint256)': TypedContractEvent<RepaymentRecordedEvent.InputTuple, RepaymentRecordedEvent.OutputTuple, RepaymentRecordedEvent.OutputObject>;
      RepaymentRecorded: TypedContractEvent<RepaymentRecordedEvent.InputTuple, RepaymentRecordedEvent.OutputTuple, RepaymentRecordedEvent.OutputObject>;
    
    };
  }